skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
resume = "ALLqbVMzsRvAJMG7J7yCyj4XdLb1PBYcqMzYWfAy7iZ1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
